### ISSUE TITLE
Notifications : Order

### ISSUE THREAD

**Issue by suriyadeepan** [FSFTN/SC15AndroidApp#3]
Order of display of notifications in Notifications activity is reversed!

**Comment by prashantbarca** [comment]
Actually. I just installed the app. I don't see notifications at all!
Samsung Grand 2. Screen just blanks out!

**Comment by suriyadeepan** [comment]
Newly registered devices are not receiving the older notifications. It should be fixed by the Rails developers in the backend. They are working on it ( I hope so ).

I added the issue to the rails repo
https://github.com/FSFTN/SC15RailsApp/issues/11
